
###################
### MY PROGRAMS ###
###################


# See https://wiki.hypr.land/Configuring/Keywords/
$terminal = ghostty
$fileManager = dolphin
$menu = hyprlauncher
$browser = firefox
#$hyprlauncher = hyprlauncher
