-- hyperland.lua
-- This files include other files in folder hyperland. 

-- --------------------------------------------------------------
-- READ THIS !!!!!!!! 
-- Always declare variables before using them (like in programming), Hyprland reads a file from top to bottom — this also applies to source includes, as including a file is like pasting its content at that exact line, so make sure to include your files in the right order.
-- --------------------------------------------------------------

--Environement vairalbes 

-- Displays 
-- require("hyprland/monitors") -- config your monitors. Generated by nwg-displays. 
-- require("hyperland/workspaces") --config generated by nwg-displays. 

-- Defaults 
-- require(hyperland.general) -- geneal conf (not using for now)
require("hyprland/keywords") -- contains all program i use and call in other conf file ($variable_name)
require("hyprland/keybinds") -- keybinding conf.
require("hyprland/autostart") -- autostart nessessary process
-- require("hyperland/monitors") -- contains all env vairable
require("hyprland/apparence") -- configuration file for visual appearance and styling (gaps, borders, animations, and decorations).
require("hyprland/input") -- configuration file for input conf adn gesture
-- require("hyprland/permissions") -- configuration file for permissions
require("hyprland/rules") -- windows rules

-- Plugins 
-- source = waybar/waybar.conf # waybar conf 
