wallpaper {
  monitor = # Change to your monitor you would like the wallapper to be set on. Use hyprctl monitors to identify your monitors. Blank if your want all monitor have the same wallpaper
  path = ~/Documents/wallpapers/wallhaven-neegvw.png # Change path to an image file or a directory containing images files. To apply a change, please superMode + W After changing this file
  fit_mode = cover 
}

# More details on https://wiki.hypr.land/Hypr-Ecosystem/hyprpaper/
