# See https://github.com/hyprwm/hyprpaper for more information

# Preload your wallpaper
preload = ~/.config/hypr/wallpapers/default.jpg

# Set the wallpaper for all monitors
wallpaper = ,~/.config/hypr/wallpapers/default.jpg

# Optionally enable splash text
splash = false
